---
title: "Lit review"
author: "Abby Lewis"
date: "2025-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
files <- list.files("../05_Lit_review", full.names = T)
all <- read_delim(files, show_col_types = F, delim = "\t") %>%
  select(TI, AB, PY)

all_classified <- all %>%
  mutate(Spring = grepl("spring", TI, ignore.case = T) | 
           grepl("spring", AB, ignore.case = T),
         Summer = grepl("summer", TI, ignore.case = T) | 
           grepl("summer", AB, ignore.case = T),
         Autumn = grepl("autumn|fall", TI, ignore.case = T) | 
           grepl("autumn|fall", AB, ignore.case = T),
         Winter = grepl("winter", TI, ignore.case = T) | 
           grepl("winter", AB, ignore.case = T),
         Rainy = grepl("rainy?[-\\s]+seasons?|wet[-\\s]+seasons?", TI, ignore.case = T) | 
           grepl("rainy?[-\\s]+seasons?|wet[-\\s]+seasons?", AB, ignore.case = T),
         Dry = grepl("dry[-\\s]+seasons?", TI, ignore.case = T) | 
           grepl("dry[-\\s]+seasons?", AB, ignore.case = T))

jpeg("../03a_Figures/change_over_time.jpg", res = 300, width = 6, height = 4, units = "in")
all_classified %>%
  filter(PY < 2025,
         PY > 1980) %>% #Incomplete
  group_by(PY) %>%
  mutate(N = n()) %>%
  pivot_longer(Spring:Dry) %>%
  mutate(Temperate = ifelse(name %in% c("Spring", "Summer", "Autumn", "Winter"), "Temperate", "Other")) %>%
  group_by(name, PY, Temperate) %>%
  summarize(n = sum(value),
            tot = unique(N)) %>%
  ggplot(aes(x = PY, y = n/tot, color = name))+
  geom_point()+
  geom_smooth()+
  facet_wrap(~Temperate, scales = "free_y")+
  theme_bw()
dev.off()

processed <- all_classified %>%
  mutate(
    # Normalize "low water", "warm water" etc. before extraction
    TI = str_replace_all(TI,
                         regex("\\b([a-z]+)[-\\s]?water\\b", 
                               ignore_case = TRUE),
                         "\\1-water"),
    AB = str_replace_all(AB,
                         regex("\\b([a-z]+)[-\\s]?water\\b", 
                               ignore_case = TRUE),
                         "\\1-water"),
    
    # Normalize "low flow", "high flow" etc. before extraction
    TI = str_replace_all(TI,
                         regex("\\b([a-z]+)[-\\s]?flow\\b", 
                               ignore_case = TRUE),
                         "\\1-flow"),
    AB = str_replace_all(AB,
                         regex("\\b([a-z]+)[-\\s]?flow\\b", 
                               ignore_case = TRUE),
                         "\\1-flow"),
    
    # Normalize rain/rainy before extraction
    TI = str_replace_all(TI, regex("\\brain[[:space:]]+season\\b", 
                                   ignore_case = TRUE), "rainy season"),
    AB = str_replace_all(AB, regex("\\brain[[:space:]]+season\\b", 
                                   ignore_case = TRUE), "rainy season"),
    
    # Normalize "non" before extraction
    TI = str_replace_all(TI, regex("\\bnon(?!-)", ignore_case = TRUE), "non-"),
    AB = str_replace_all(AB, regex("\\bnon(?!-)", ignore_case = TRUE), "non-"),
    
    # Normalize ice free before extraction
    TI = str_replace_all(TI, regex("\\bice[[:space:]]+free[[:space:]]+season\\b", 
                                   ignore_case = TRUE), "ice-free season"),
    AB = str_replace_all(AB, regex("\\bice[[:space:]]+free[[:space:]]+season\\b", 
                                   ignore_case = TRUE), "ice-free season")
  ) %>%
  #Extract
  mutate(
    Type_TI = str_extract_all(TI, regex("\\b[\\w-]+(?=[\\s-]+seasons?\\b)", ignore_case = TRUE)),
    Type_AB = str_extract_all(AB, regex("\\b[\\w-]+(?=[\\s-]+season?\\b)", ignore_case = TRUE)),

    #Combine
    SeasonWords = map2(Type_TI, Type_AB, ~ unique(tolower(c(.x, .y))))
  )

# Define words to remove
filler_words <- c(
  #Prepositions
  "in", "on", "at", "by", "between", "of", "to", 
  "for","with", "within", "from","across",
  #Articles
  "a", "the", "that", "this", 
  #Conjunctions
  "and", "or",
  #Other
  "different", "each","same","one","per", "single", 
  "every", "multi", "any", "given", "following", 
  "either", "previous", "other")
temporal_phases <- c("early", "mid", "late", "first", "second", 
                     "end-of", "whole", "entire", "two", "four", 
                     "all", "normal", "peak")

#Define season types
temperate <- c("spring", "summer", "autumn", "winter", "fall")
flora <- c("wintering", "growth", "growing", "non-growing", 
           "vegetative", "productive", "non-productive",
           "dormant", "bloom", "blooming", "vegetation", "fire")
fauna <- c("breeding", "spawning", "reproductive", "mating",
           "nesting","non-breeding", "migration","active")
ice <- c("ice-covered", "ice-free", "open-water", "melt", 
         "melting", "thaw", "snowmelt", "ice", "ice-cover", 
         "snow", "snow-free", "ablation")
stratification <- c("stratified", "mixing")
temperature <- c("cold", "cool", "warm", "hot", "warmer", "heating")
hydrology <- c("dry", "rainy", "wet","runoff", "hydrological", 
               "flood", "flooding", "high-water", "low-water", "high-flow",
               "low-flow", "non-flood", "rainfall", "monsoon",
               "post-monsoon", "pre-monsoon", "non-monsoon", "drought")
agriculture <- c("irrigation", "rice-growing", "cropping", 
                 "planting", "harvest", "wheat", "rice")
economic <- c("fishing", "angling", "closed",
                "hunting", "tourist", "bathing", "swimming")
research <- c("field", "sampling")

#Check
#processed$AB[processed$SeasonWords == "active"]

season_word_counts <- processed %>%
  select(SeasonWords) %>%
  unnest(SeasonWords) %>%
  mutate(SeasonWords = tolower(SeasonWords),
         SeasonWords = gsub("[[:space:]-]$", "", SeasonWords)) %>%
  filter(!SeasonWords %in% filler_words,
         !SeasonWords %in% temporal_phases,
         !is.na(SeasonWords)) %>%   # remove filler words
  mutate(
    Type = case_when(
      SeasonWords %in% temperate ~ "Temperate",
      SeasonWords %in% flora ~ "Flora",
      SeasonWords %in% fauna ~ "Fauna",
      SeasonWords %in% ice ~ "Ice/Snow",
      SeasonWords %in% stratification ~ "Stratification",
      SeasonWords %in% temperature ~ "Temperature",
      SeasonWords %in% hydrology ~ "Hydrology",
      SeasonWords %in% agriculture ~ "Agriculture",
      SeasonWords %in% economic ~ "Economic",
      SeasonWords %in% research ~ "Research",
      TRUE ~ "Other"
    )
  ) %>%
  count(Type, SeasonWords, sort = TRUE)

# Plot the results
jpeg("../03a_Figures/count.jpg", res = 300, width = 4, height = 12, units = "in")
season_word_counts %>%
  filter(n > 10) %>%
  ggplot(aes(y = reorder(SeasonWords, n), x = n, fill = Type)) +
  geom_col() +
  ylab("Word before 'season'")+
  xlab("Frequency")+
  theme_minimal(base_size = 14)
dev.off()
```

```{r}
season_word_counts_plot <- season_word_counts %>%
  filter(n > 10)

sum_seas <- sum(season_word_counts_plot$n, na.rm = T)

seasons_by_cat <- season_word_counts_plot %>%
  filter(n > 10) %>%
  group_by(Type) %>%
  summarize(total_by_type = sum(n)) %>% 
  arrange(desc(total_by_type)) %>%
  mutate(Type = paste0(Type, " (n = ", total_by_type, ")"))

compute_angle = function(perc){
  angle = -1
  
  if(perc < 0.5) # 1st half [90, -90]
    angle = (180 - (perc/0.5) * 180) - 90
  else # 2nd half [90, -90]
    angle = (90 - ((perc - 0.5)/0.5) * 180)

  return(angle)
}

secondLevel = seasons_by_cat %>%
  arrange(desc(total_by_type)) %>%
  mutate(running = cumsum(total_by_type), 
         pos=running - total_by_type/2) %>% 
  rowwise() %>% 
  mutate(angle = compute_angle(pos / sum_seas))

thirdLevel = season_word_counts_plot %>%
  group_by(Type) %>%
  mutate(total_by_type = sum(n)) %>% 
  ungroup() %>%
  arrange(desc(total_by_type),
          desc(n)) %>%
  mutate(running = cumsum(n), 
         pos=running - n/2,
         Type = paste0(Type, " (n = ", total_by_type, ")")) %>% 
  rowwise() %>% 
  mutate(angle = compute_angle(pos / sum_seas),
         hjust = ifelse(pos/sum_seas > 0.5, 1, 0),
         label = SeasonWords, #paste0(SeasonWords, " (", comma(n), ")"),
         label = ifelse(n < 75, "", label))

secondLevel$Type <- factor(secondLevel$Type, 
                           levels = rev(seasons_by_cat$Type))

thirdLevel$Type <- factor(thirdLevel$Type, 
                          levels = rev(seasons_by_cat$Type))

colors <- c("#64c7cc", #hydrology
            "#11592b", #growing
            "#8f6501", #fauna
            "grey", #temperate
            "#8AB4E3", #ice
            "#993355", #temperature
            "#ddbb66", #economic
            "#79ad24",#ag
            "#66450c",#research
            "#F6A2A2")#stratification
            #"grey20") #other

jpeg("../03a_Figures/Sunburst.jpg", res = 300, width = 6, height = 5, units = "in")
ggplot() +
  geom_bar(data=thirdLevel,
           aes(x=5, y=n, fill = Type),
           color = "white",linewidth = 0.2,
           position='stack', stat='identity', 
           alpha = 0.5, width = 2) +
  geom_bar(data=secondLevel,
           aes(x=3, y=total_by_type, fill=Type),
           width = 2,color = "white",linewidth = 0.2,
           position='stack', stat='identity')+
  
  #geom_segment(data=secondLevel %>% ungroup() %>% mutate(prev = lag(running),
  #                                         prev = ifelse(is.na(prev), 0, prev)),
  #         aes(x=4, y = prev, yend=running, color=Type), linewidth = 1.5)+
  geom_text(data=thirdLevel, 
            aes(label=label, x=6.2, y=pos, angle=angle, 
                hjust = hjust, color = Type), show.legend = F
            ) +
  xlim(c(0,8))+
  coord_polar('y')+
  scale_color_manual(values= colors, breaks = seasons_by_cat$Type) + 
  scale_fill_manual(values = colors, breaks = seasons_by_cat$Type) + 
  theme_void()+
  ggtitle('Words that precede "season"')+
  guides(fill = guide_legend(title = NULL, nrow = 4)) + 
  theme(
    plot.title = element_text(hjust = 0.5, vjust = -6, size = 14),
    legend.position = "bottom",
    legend.box.margin = margin(t = -10),
    legend.margin = margin(t = -5),
    legend.spacing.y = unit(0, "pt"),
    plot.margin = margin(0, 0, 0, 0)
  )
dev.off()
```

```{r}
library(stringi)
library(data.table)

#https://simplemaps.com/data/world-cities
places <- fread("../01a_Raw_data/worldcities.csv")

# Load data
countries <- unique(places$country)
places[, city_lower := tolower(city)]
places[, country_lower := tolower(country)]

# Extract country info
countries <- unique(places[, .(country, iso2, iso3)])
countries[, `:=`(
  country_lower = tolower(country),
  iso2_lower = tolower(iso2),
  iso3_lower = tolower(iso3)
)]

# --- Create search vectors ---
countries_lower <- countries$country_lower
iso2_lower <- na.omit(countries$iso2_lower)
iso3_lower <- na.omit(countries$iso3_lower[!countries$iso3_lower=="and"])

papers <- setDT(processed %>%
                  select(TI, AB, SeasonWords))
places <- setDT(places)
papers[, full_text := tolower(paste(TI, AB))]

# Vectorize country detection
detect_country <- function(text) {
  # Match full country name
  idx <- which(stri_detect_fixed(text, countries$country_lower))
  if (length(idx) > 1) return("Multi")
  if (length(idx) > 0) return(countries$country[idx[1]])
  
  # Match ISO3
  idx <- which(stri_detect_regex(text, paste0("\\b", countries$iso3_lower, "\\b")))
  if (length(idx) > 1) return("Multi")
  if (length(idx) == 1) return(countries$country[idx])
  
  return(NA_character_)
}


# Vectorize city detection
detect_city_country <- function(text) {
  matches <- places$city_lower[stri_detect_fixed(text, places$city_lower)]
  if (length(matches) > 1) return("Multi")
  if (length(matches) == 0) return(NA_character_)
  unique(places[c(city_lower %in% matches), country_lower])[1]
}

# Apply
papers[, Country := {
  ctry <- detect_country(full_text)
  if (is.na(ctry)) detect_city_country(full_text) else ctry
}, by = 1:nrow(papers)]  

spat2 <- papers %>%
  as.data.frame()

sum(!is.na(spat2$Country))/nrow(spat2) #Currently matching ~1/2 of abstracts

top5 <- spat2 %>%
  group_by(Country) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  filter(!Country == "Multi",
         !is.na(Country)) %>%
  head(5) %>%
  pull(Country)

season_word_counts_spat <- spat2 %>%
  filter(Country %in% top5) %>%
  select(SeasonWords, Country) %>%
  unnest(SeasonWords) %>%
  mutate(SeasonWords = tolower(SeasonWords),
         SeasonWords = gsub("[[:space:]-]$", "", SeasonWords)) %>%
  filter(!SeasonWords %in% filler_words,
         !SeasonWords %in% temporal_phases,
         !is.na(SeasonWords)) %>% 
  mutate(
    Type = case_when(
      SeasonWords %in% temperate ~ "Temperate",
      SeasonWords %in% flora ~ "Flora",
      SeasonWords %in% fauna ~ "Fauna",
      SeasonWords %in% ice ~ "Ice/Snow",
      SeasonWords %in% stratification ~ "Stratification",
      SeasonWords %in% temperature ~ "Temperature",
      SeasonWords %in% hydrology ~ "Hydrology",
      SeasonWords %in% agriculture ~ "Agriculture",
      SeasonWords %in% economic ~ "Economic",
      SeasonWords %in% research ~ "Research",
      TRUE ~ "Other"
    )
  ) %>%
  count(Type, SeasonWords, Country, sort = TRUE)

season_word_counts_plot <- season_word_counts_spat %>%
    filter(n > 10)
```

Facet plot
```{r}
seasons_by_cat_i <- season_word_counts_plot %>%
  filter(Country %in% top5) %>%
  group_by(Type, Country) %>%
  summarize(total_by_type = sum(n)) %>% 
  arrange(desc(total_by_type))

secondLevel = seasons_by_cat_i %>%
  group_by(Country) %>%
  arrange(desc(total_by_type)) %>%
  mutate(running = cumsum(total_by_type), 
         pos=running - total_by_type/2,
         sum_seas = sum(total_by_type),
         Country_label = paste0(Country, "(n = ", sum_seas, ")")) %>% 
  rowwise() %>% 
  mutate(angle = compute_angle(pos / sum_seas))

thirdLevel = season_word_counts_plot %>%
  filter(Country %in% top5) %>%
  group_by(Type, Country) %>%
  mutate(total_by_type = sum(n)) %>% 
  group_by(Country) %>%
  arrange(desc(total_by_type),
          desc(n)) %>%
  mutate(running = cumsum(n), 
         pos=running - n/2,
         sum_seas = sum(total_by_type),
         Country_label = paste0(Country, "(n = ", sum_seas, ")")) %>% 
  rowwise() %>% 
  mutate(angle = compute_angle(pos / sum_seas),
         hjust = ifelse(pos/sum_seas > 0.5, 1, 0),
         label = SeasonWords, #paste0(SeasonWords, " (", comma(n), ")"),
         label = ifelse(n < 30, "", label))

secondLevel$Type <- factor(secondLevel$Type, 
                           levels = rev(sub(" \\(.+\\)","",seasons_by_cat$Type)))

thirdLevel$Type <- factor(thirdLevel$Type, 
                          levels = rev(sub(" \\(.+\\)","",seasons_by_cat$Type)))

ggplot() +
  geom_bar(data=thirdLevel,
           aes(x=5, y=n, fill = Type),
           color = "white",linewidth = 0.2,
           position='stack', stat='identity', 
           alpha = 0.5, width = 2) +
  geom_bar(data=secondLevel,
           aes(x=3, y=total_by_type, fill=Type),
           width = 2,color = "white",linewidth = 0.2,
           position='stack', stat='identity')+
  xlim(c(0,7))+
  coord_polar('y')+
  scale_color_manual(values = colors, breaks = sub(" \\(.+\\)","",seasons_by_cat$Type)) + 
  scale_fill_manual(values = colors, breaks = sub(" \\(.+\\)","",seasons_by_cat$Type)) + 
  theme_void()+
  guides(fill = guide_legend(title = NULL, nrow = 4)) + 
  theme(
    plot.title = element_text(hjust = 0.5, vjust = -6, size = 14),
    legend.position = "bottom",
    legend.box.margin = margin(t = -10),
    legend.margin = margin(t = -5),
    legend.spacing.y = unit(0, "pt"),
    plot.margin = margin(0, 0, 0, 0)
  )+
  facet_wrap(~Country_labe, scales = "free_y")
```

