---
title: "Plot"
author: "Abby Lewis"
date: "2024-02-29"
output: html_document
---

# Set-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(ggnewscale) # For multiple color scales on the discrete panel

#The ../03a_Figures folder is not pushed to GitHub
if(!file.exists("../03a_Figures")){dir.create("../03a_Figures")}

#Southern hemisphere lakes
sh_lakes <- c("Rerewhakaaitu")

LAKES <- c("Lake Erken (2018)", #59.83917
           "Arendsee (2020)", #52.89099
           "Lake Ägeri (2023)", #47.1213
           "Midway Pond (2023)", #44.9312
           "Lake Sunapee (2008)", #43.3802
           "Mohonk Lake (2017)", #41.76598
           "Beaverdam Reservoir (2021)", #37.3164
           "Lake Rerewhakaaitu (2022-2023)") #-38.2936
```

# Discrete

NOTE: add color for mixed period

```{r}
#Load discrete data
#BVR
bvr_ice <- read.csv("../01b_Processed_data/BVR_ice.csv") 
bvr_strat <- read.csv("../01b_Processed_data/BVR_stratification_discrete.csv") 
#General
temperate_raw <- read.csv("../01b_Processed_data/Temperate_seasons.csv")
#Rerewhakaaitu
rere_strat <- read.csv("../01b_Processed_data/Rerewhakaaitu_stratification_discrete.csv") 
rere_ice <- read.csv("../01b_Processed_data/Rerewhakaaitu_ice.csv")
#Sunapee
sun_strat <- read.csv("../01b_Processed_data/Sunapee_stratification_discrete.csv") 
sun_ice <- read.csv("../01b_Processed_data/Sunapee_ice.csv") 
#Erken
erken_strat <- read.csv("../01b_Processed_data/Erken_stratification_discrete.csv") 
erken_ice <- read.csv("../01b_Processed_data/Erken_ice.csv") 
#Mohonk
mohonk_strat <- read.csv("../01b_Processed_data/Mohonk_stratification_discrete.csv") 
mohonk_ice <- read.csv("../01b_Processed_data/Mohonk_ice.csv") 
#Arendsee
arendsee_strat <- read.csv("../01b_Processed_data/Arendsee_stratification_discrete.csv") 
arendsee_ice <- read.csv("../01b_Processed_data/Arendsee_ice.csv") 
#Midway
midway_strat <- read.csv("../01b_Processed_data/Midway_stratification_discrete.csv") 
#Arendsee
Ägeri_strat <- read.csv("../01b_Processed_data/Ägeri_stratification_discrete.csv") 
Ägeri_ice <- read.csv("../01b_Processed_data/Ägeri_ice.csv") 

#Format
in_lake <- bvr_strat %>% 
  full_join(sun_strat) %>%
  full_join(rere_strat) %>%
  full_join(erken_strat) %>%
  full_join(mohonk_strat) %>%
  full_join(arendsee_strat) %>%
  full_join(midway_strat) %>%
  full_join(Ägeri_strat) %>%
  mutate(Method = "Stratification",
         x = start,
         xend = end,
         Lake = factor(Lake, levels = LAKES))

ice_format <- bvr_ice %>%
  full_join(rere_ice) %>%
  full_join(sun_ice) %>%
  full_join(erken_ice) %>%
  full_join(mohonk_ice) %>%
  full_join(arendsee_ice) %>%
  full_join(Ägeri_ice) %>%
  mutate(Lake = factor(Lake, levels = LAKES))

#Format
temperate <- temperate_raw %>% filter(is.na(start)) #make empty df
for(lake in unique(in_lake$Lake)) {
  hemi <- ifelse(lake %in% sh_lakes, "Southern", "Northern")
  temperate <- temperate %>%
    full_join(temperate_raw %>% mutate(Lake = lake) %>%
                filter(Hemisphere == hemi))
}
temperate <- temperate %>%
  mutate(Lake = factor(Lake, levels = LAKES))

#Plot
#First the temperate metrics
discrete_temperate <- temperate %>%
  filter(Method == "Months") %>%
  ggplot(aes(y = Method, 
             yend = Method, 
             x = start, 
             xend = end, 
             color = Season)) +
  geom_segment(lwd = 5) +
  theme_bw() +
  ggtitle("Discrete seasonal clasifications") +
  scale_color_manual("Temperate\nseasons",
                     values = c("grey80", "grey67", "grey37", "grey10", 
                                "grey", "grey", "grey", "grey", "grey"), #placeholders
                     breaks = c("Winter", "Spring", "Summer", "Autumn")) +
  scale_x_continuous(breaks = c(0, 90, 183, 276, 365),
                 labels = c("Winter\nsolstice", "Spring\nequinox", 
                            "Summer\nsolstice", "Autumn\nequinox", "Winter\nsolstice")) +
  guides(color = guide_legend(ncol = 1, title.position="top")) +
  facet_wrap(~Lake, ncol = 1)

#Add in-lake data (with separate color legend)
discrete_strat <- discrete_temperate +
  ggnewscale::new_scale_color() +
  geom_segment(data = in_lake, 
               aes(y = Method, 
                   yend = Method, 
                   x = start, 
                   xend = end, 
                   color = Season), 
               lwd = 5) +
  scale_color_manual("Stratification", values = c("#FACFCF", "#F49090", "#CC4949"),
                     breaks = c("Inversely\nstratified", "Mixed", "Stratified")) +
  guides(color = guide_legend(ncol = 1, title.position="top")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        legend.title = element_text(vjust = 1),
        panel.grid.major.x = element_line(color = "grey70"),
        panel.grid.major.y = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.height = unit(0, "mm"),
        legend.key.spacing.y = unit(0, "mm"),
        panel.grid.minor = element_blank()) +
  facet_wrap(~Lake, ncol = 1)
discrete_strat

discrete_ice <- discrete_strat +
  ggnewscale::new_scale_color() +
  geom_segment(data = ice_format,
               aes(y = Method, 
                   yend = Method, 
                   x = start, 
                   xend = end, 
                   color = Season), 
               lwd = 5) +
  scale_color_manual("Ice", values = c("#8AB4E3", "#E5EDF7"),
                     breaks = c("Open water", "Ice")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        legend.title = element_text(vjust = 1),
        panel.grid.major.x = element_line(color = "grey70"),
        panel.grid.major.y = element_blank(),
        legend.key.height = unit(0, "mm"),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.spacing.y = unit(0, "mm"),
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(ncol = 1, title.position="top")) +
  facet_wrap(~Lake, ncol = 1)

#View
discrete_ice
```

# Continuous

```{r}
#Load data
#BVR
bvr_catwalk_format <- read.csv("../01b_Processed_data/BVR_catwalk.csv")
bvr_met_format <- read.csv("../01b_Processed_data/BVR_met.csv")
bvr_strat <- read.csv("../01b_Processed_data/BVR_stratification_continuous.csv")
#Rerewhakaaitu
rere_in_lake <- read.csv("../01b_Processed_data/Rerewhakaaitu_continuous.csv")
rere_strat <- read.csv("../01b_Processed_data/Rerewhakaaitu_stratification_continuous.csv")
rere_met <- read.csv("../01b_Processed_data/Rerewhakaaitu_met.csv")
#Sunapee
sun_in_lake <- read.csv("../01b_Processed_data/Sunapee_continuous.csv")
sun_strat <- read.csv("../01b_Processed_data/Sunapee_stratification_continuous.csv")
sun_met <- read.csv("../01b_Processed_data/Sunapee_met.csv")
#Erken
erken_in_lake <- read.csv("../01b_Processed_data/Erken_continuous.csv")
erken_strat <- read.csv("../01b_Processed_data/Erken_stratification_continuous.csv")
erken_met <- read.csv("../01b_Processed_data/Erken_met.csv")
#Mohonk
mohonk_in_lake <- read.csv("../01b_Processed_data/Mohonk_continuous.csv")
mohonk_strat <- read.csv("../01b_Processed_data/Mohonk_stratification_continuous.csv")
#Arendsee
arendsee_in_lake <- read.csv("../01b_Processed_data/Arendsee_continuous.csv")
arendsee_strat <- read.csv("../01b_Processed_data/Arendsee_stratification_continuous.csv")
arendsee_met <- read.csv("../01b_Processed_data/Arendsee_met.csv")
#Midway
midway_in_lake <- read.csv("../01b_Processed_data/Midway_continuous.csv")
midway_strat <- read.csv("../01b_Processed_data/Midway_stratification_continuous.csv")
#Ägeri
Ägeri_in_lake <- read.csv("../01b_Processed_data/Ägeri_continuous.csv")
Ägeri_strat <- read.csv("../01b_Processed_data/Ägeri_stratification_continuous.csv")
Ägeri_met <- read.csv("../01b_Processed_data/Ägeri_met.csv")

#Format
#A bit of magic to get explicit NAs
all <- bvr_catwalk_format %>%
  full_join(bvr_met_format) %>%
  full_join(bvr_strat) %>%
  full_join(rere_in_lake) %>%
  full_join(rere_strat) %>%
  full_join(rere_met) %>%
  full_join(sun_in_lake) %>%
  full_join(sun_strat) %>%
  full_join(sun_met) %>%
  full_join(erken_in_lake) %>%
  full_join(erken_strat) %>%
  full_join(erken_met) %>%
  full_join(mohonk_in_lake) %>%
  full_join(mohonk_strat) %>%
  full_join(arendsee_in_lake) %>%
  full_join(arendsee_strat) %>%
  full_join(arendsee_met) %>%
  full_join(midway_in_lake) %>%
  full_join(midway_strat) %>%
  full_join(Ägeri_in_lake) %>%
  full_join(Ägeri_strat) %>%
  full_join(Ägeri_met)

full <- all %>%
  expand(Variable, yday, Lake)

continuous_data <- all %>%
  right_join(full) %>%
  mutate(Variable = factor(Variable, 
                           levels = c("Surface_temperature", 
                                      "AirTemp_C_Average", 
                                      "Surface_chla", 
                                      "Surface_DO",
                                      "Bottom_DO",
                                      "Turbidity",
                                      "Shortwave",
                                      "Diff_Dens_surf_bot"),
                           labels = c("Surface temperature", 
                                      "Air temperature",
                                      "Surface chlorophyll-a",
                                      "Surface DO",
                                      "Bottom-water DO",
                                      "Surface turbidity",
                                      "Solar radiation",
                                      "Epi-hypo dens. difference"))) %>%
  filter(!is.na(Variable)) %>%
  group_by(Variable, Lake) %>%
  mutate(Value = ((Value) - min(Value, na.rm = T))/
           (max((Value) - min(Value, na.rm = T), na.rm = T))) %>%
  mutate(x = yday) %>%
  mutate(var_class = ifelse(Variable %in% c("Surface chlorophyll-a", 
                                            "Bottom-water DO",
                                            "Surface turbidity",
                                            "Surface DO"), 
                            "Bio/chem", "Phys"),
         Lake = factor(Lake, levels = LAKES))

#Plot
continuous <- continuous_data %>%
  filter(!Variable %in% c("Surface turbidity","Surface DO")) %>%
  ggplot(aes(x = x, y = Value * 100, color = Variable)) +
  scale_color_manual(values = c("#6B7CB3","#1F363D","#8DD65C", "lightblue","#FFC233", "#F05D5E")) +
  geom_line(alpha = 0.2) +
  geom_smooth(se = F, method = "gam") +
  theme_bw() + 
  ylab("% of range") +
  ggtitle("Seasonally-varying parameters")  +
  guides(color = guide_legend(ncol = 1)) +
  scale_x_continuous(breaks = c(0, 90, 183, 276, 365),
                 labels = c("Winter\nsolstice", "Spring\nequinox", 
                            "Summer\nsolstice", "Autumn\nequinox", "Winter\nsolstice")) +
  facet_wrap(~Lake, ncol = 1, scales = "free_y") +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.height = unit(3, "mm"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey80"))

#View
continuous
```

# Combine and save

```{r}
jpeg("../03a_Figures/Seasons_data.jpg", width = 9, height = 10, units = "in", res = 300)
ggarrange(discrete_strat, continuous, align = "h")
dev.off()

jpeg("../03a_Figures/Seasons_data_ice.jpg", width = 8.5, height = 9, units = "in", res = 300)
ggarrange(discrete_ice, continuous, align = "h")
dev.off()
```
```{r}
discrete_ice2 <- discrete_strat +
  ggnewscale::new_scale_color() +
  geom_segment(data = ice_format,
               aes(y = Method, 
                   yend = Method, 
                   x = start, 
                   xend = end, 
                   color = Season), 
               lwd = 5) +
  scale_color_manual("Ice", values = c("#8AB4E3", "#E5EDF7"),
                     breaks = c("Open water", "Ice")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        legend.title = element_text(vjust = 1),
        panel.grid.major.x = element_line(color = "grey70"),
        panel.grid.major.y = element_blank(),
        legend.key.height = unit(0, "mm"),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.spacing.y = unit(0, "mm"),
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(ncol = 1, title.position="top")) +
  facet_wrap(~Lake, ncol = 1) +
  labs(subtitle = "")

continuous2 <- continuous_data %>%
  filter(var_class == "Bio/chem") %>%
  ggplot(aes(x = x, y = Value * 100, color = Variable)) +
  scale_color_manual(values = c("#8DD65C", "blue","#7b32c9","black")) +
  geom_line(alpha = 0.2) +
  geom_smooth(se = F, method = "gam") +
  theme_bw() + 
  ylab("% of max") +
  #ggtitle("Seasonally-varying parameters")  +
  guides(color = guide_legend(ncol = 1)) +
  scale_x_continuous(breaks = c(0, 90, 183, 276, 365),
                 labels = c("Winter\nsolstice", "Spring\nequinox", 
                            "Summer\nsolstice", "Autumn\nequinox", "Winter\nsolstice")) +
  facet_wrap(~Lake, ncol = 1)+ 
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.height = unit(3, "mm"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey80"),
        #strip.text.x = element_blank()
        )+
  labs(subtitle = "Biological/chemical")

continuous3 <- continuous_data %>%
  filter(var_class == "Phys") %>%
  ggplot(aes(x = x, y = Value * 100, color = Variable)) +
  scale_color_manual(values = c("#6B7CB3","#1F363D", "#FFC233","#F05D5E")) +
  geom_line(alpha = 0.2) +
  geom_smooth(se = F, method = "gam") +
  theme_bw() + 
  ylab("% of max") +
  guides(color = guide_legend(ncol = 1)) +
  scale_x_continuous(breaks = c(0, 90, 183, 276, 365),
                 labels = c("Winter\nsolstice", "Spring\nequinox", 
                            "Summer\nsolstice", "Autumn\nequinox", "Winter\nsolstice")) +
  ggtitle("Seasonally-varying parameters")  +
  facet_wrap(~Lake, ncol = 1) +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.height = unit(3, "mm"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey80"),
        #strip.text.x = element_blank()
        )+
  labs(subtitle = "Physical")

jpeg("../03a_Figures/Seasons_data_ice2.jpg", width = 10, height = 10, units = "in", res = 300)
ggarrange(discrete_ice2, continuous3, continuous2, align = "h", nrow = 1, widths = c(1.2, 1,1))
dev.off()
```

