---
title: "Plot"
author: "Abby Lewis"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)

#Because the Figures folder is not pushed to GitHub
if(!file.exists("../Figures")){dir.create("../Figures")}
```

# Discrete

```{r}
ice_format <- read.csv("../Processed_data/FCR_ice.csv") %>%
  mutate(Season = ifelse(Event == "Ice on", "Winter", "Spring"))

months_format <- data.frame(Season = c("Spring", "Summer", "Autumn", "Winter"),
                            yday = c(yday("2021-03-01"),
                                     yday("2021-06-01"),
                                     yday("2021-09-01"),
                                     yday("2021-12-01")))

solstice_format <- data.frame(Season = c("Spring", "Summer", "Autumn", "Winter"),
                              yday = c(yday("2021-03-20"),
                                       yday("2021-06-20"),
                                       yday("2021-09-22"),
                                       yday("2021-12-21")))
discrete <- ice_format %>%
  ggplot()+
  geom_vline(aes(xintercept = yday, lty = Season, color = "Ice")) +
  geom_vline(aes(xintercept = yday, color = "Month", lty = Season), 
             data = months_format) +
  geom_vline(aes(xintercept = yday, color = "Solstice/equinox", lty = Season), 
             data = solstice_format) +
  xlim(0, 365)+
  scale_color_manual(values = c("lightblue", "black", "goldenrod")) +
  scale_linetype_manual(values = c(1, 2, 3, 4), 
                        breaks = c("Spring", "Summer", "Autumn", "Winter")) +
  theme_bw()+
  theme(legend.title = element_blank()) + 
  ggtitle("Discrete seasonal clasifications") +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        panel.grid = element_blank()) +
  guides(color = guide_legend(ncol=1),
         lty = guide_legend(ncol=1))

discrete
```

```{r}
ice_format <- read.csv("../Processed_data/FCR_ice.csv") %>%
  mutate(Season = ifelse(Event == "Ice on", "Winter", "Spring"))

ice_format2 <- ice_format %>%
  mutate(group = rep(1:(nrow(ice_format)/2), each = 2),
         point = rep(c("start", "end"), times  = nrow(ice_format)/2)) %>%
  select(-Event, -Season) %>%
  pivot_wider(names_from = point, values_from = yday) %>%
  mutate(Season = "Winter")

strat <- read.csv("../Processed_data/FCR_stratification_metrics.csv") %>%
  filter(Variable == "Diff_Dens_surf_9") %>%
  mutate(Strat = ifelse(Value > 0.1, "Summer", "Mixed")) %>%
  filter(!is.na(Value)) %>%
  filter(!Strat == lag(Strat)) %>%
  full_join(data.frame(Variable = "Diff_Dens_surf_9", yday = 0, Strat = "Mixed")) %>%
  arrange(yday) %>%
  mutate(end = lead(yday, default = 365)) %>%
  rename(start = yday, Season = Strat) %>%
  filter(Season == "Summer")

months_format2 <- data.frame(Season = c("Spring", "Summer", "Autumn", "Winter", "Winter"),
                            start = c(yday("2021-03-01"),
                                     yday("2021-06-01"),
                                     yday("2021-09-01"),
                                     yday("2021-12-01"),
                                     yday("2021-01-01")),
                            end = c(yday("2021-06-01"),
                                    yday("2021-09-01"),
                                    yday("2021-12-01"),
                                    yday("2021-12-31"),
                                    yday("2021-03-01")))

solstice_format2 <- data.frame(Season = c("Spring", "Summer", "Autumn", "Winter", "Winter"),
                              start = c(yday("2021-03-20"),
                                       yday("2021-06-20"),
                                       yday("2021-09-22"),
                                       yday("2021-12-21"),
                                       yday("2021-01-01")),
                              end = c(yday("2021-06-20"),
                                      yday("2021-09-22"),
                                      yday("2021-12-21"),
                                      yday("2021-12-31"),
                                      yday("2021-03-20")))

discrete2 <- months_format2 %>%
  mutate(Method = "Months") %>%
  full_join(solstice_format2 %>% mutate(Method = "Solstice/equinox")) %>%
  full_join(ice_format2 %>% mutate(Method = "Ice/stratification")) %>%
  full_join(strat %>% mutate(Method = "Ice/stratification")) %>%
  ggplot(aes(y = Method, yend = Method, x = start, xend = end, color = Season)) +
  geom_segment(lwd = 5) +
  theme_bw() +
  ggtitle("Discrete seasonal clasifications") +
  scale_color_manual(values = c("lightblue", "pink", "goldenrod2", "#cc5500"),
                     breaks = c("Winter", "Spring", "Summer", "Autumn")) +
  theme(legend.position = "bottom",
        axis.title.x = element_blank()) +
  guides(color = guide_legend(ncol=1))

discrete2
```

# Continuous

```{r}
catwalk_format <- read.csv("../Processed_data/FCR_catwalk.csv")
met_format <- read.csv("../Processed_data/FCR_met.csv")
strat <- read.csv("../Processed_data/FCR_stratification_metrics.csv")

continuous <- catwalk_format %>%
  full_join(met_format) %>%
  full_join(strat) %>%
  filter(!is.na(Value)) %>%
  mutate(Variable = factor(Variable, 
                           levels = c("EXOTemp_C_1", 
                                      "AirTemp_C_Average", 
                                      "EXOChla_ugL_1", 
                                      "ShortwaveRadiationDown_Average_W_m2",
                                      "Diff_Dens_surf_9"),
                           labels = c("Surface temperature", 
                                      "Air temperature",
                                      "Surface chlorophyll-a",
                                      "Shortwave",
                                      "Epi-hypo dens. difference"))) %>%
  filter(!is.na(Variable)) %>%
  group_by(Variable) %>%
  mutate(Value = (Value)/(max(Value))) %>%
  ggplot(aes(x = yday, y = Value * 100, color = Variable)) +
  scale_color_manual(values = c("purple","pink", "#26c9a3", "goldenrod", "grey50")) +
  geom_line(alpha = 0.3) +
  geom_smooth(se = F, method = "gam") +
  theme_bw() + 
  ggtitle("Seasonally-varying parameters") +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank()) +
  guides(color=guide_legend(ncol=1)) +
  ylab("% of max")

continuous
```

# Combine

```{r}
jpeg("../Figures/Seasons_data.jpg", width = 6, height = 3.5, units = "in", res = 300)
ggarrange(discrete + ylab("FCR"), continuous, align = "h")
dev.off()

jpeg("../Figures/Seasons_data2.jpg", width = 8, height = 3.5, units = "in", res = 300)
ggarrange(discrete2 + ylab("FCR"), continuous, align = "h")
dev.off()
```

