---
title: "FCR"
author: "Abby Lewis"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rLakeAnalyzer)
```

```{r}
options(timeout=6000)
catwalk <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/271/8/fbb8c7a0230f4587f1c6e11417fe9dce")

catwalk_format <- catwalk %>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date)) %>%
  filter(Year == 2021) %>%
  group_by(Date) %>%
  summarize(EXOTemp_C_1 = mean(EXOTemp_C_1, na.rm = T),
            EXOChla_ugL_1 = mean(EXOChla_ugL_1, na.rm = T)) %>%
  mutate(yday = yday(Date)) %>%
  pivot_longer(cols = c(EXOTemp_C_1, EXOChla_ugL_1), 
               names_to = "Variable", values_to = "Value")

write.csv(catwalk_format, "../01b_Processed_data/FCR_catwalk.csv", row.names = F)

#### stratification metric calcs
## get bathymetry data
edi_bathy <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1254/1/f7fa2a06e1229ee75ea39eb586577184" )

bathy_schmidt <- edi_bathy %>% 
  filter(Reservoir == 'FCR') %>% 
  dplyr::select(Depth_m, SA_m2) %>% 
  dplyr::rename(depths = 1,
         areas = 2)

## set up daily thermistor data 
catwalk_strat <- catwalk |> 
  mutate(Date = as.Date(DateTime),
         Year = year(Date)) |> 
  filter(Year == 2021) |> 
  select(Date, 4:13) |> #get just date and thermistors
  group_by(Date) |> 
  summarise_if(is.numeric, mean, na.rm = TRUE) |>  # get daily temp data
  rename(datetime = Date,
       wtr_00.1 = ThermistorTemp_C_surface,
       wtr_01.0 = ThermistorTemp_C_1,
       wtr_02.0 = ThermistorTemp_C_2,
       wtr_03.0 = ThermistorTemp_C_3,
       wtr_04.0 = ThermistorTemp_C_4,
       wtr_05.0 = ThermistorTemp_C_5,
       wtr_06.0 = ThermistorTemp_C_6,
       wtr_07.0 = ThermistorTemp_C_7,
       wtr_08.0 = ThermistorTemp_C_8,
       wtr_09.0 = ThermistorTemp_C_9) #rename to match schmidt and bouyancy functions 
  
#calc schmidt
fcr_schmidt <- rLakeAnalyzer::ts.schmidt.stability(catwalk_strat, bathy_schmidt, na.rm = T)

#calc buoyancy freq
fcr_buoy <- rLakeAnalyzer::ts.buoyancy.freq(catwalk_strat, na.rm = F) |> 
  rename(buoy_freq = n2) #lots of NAs? not sure why 

#calc density or temp difference from surface to 9m
fcr_dens <- catwalk_strat |> 
  mutate(Diff_C_surf_9 = wtr_00.1 - wtr_09.0,
         Diff_Dens_surf_9 = water.density(wtr_09.0) - water.density(wtr_00.1),
         Strat_1C_surf_9 = ifelse(Diff_C_surf_9 < 1, "Not_Strat", "Strat"),
         Strat_Dens0.1_surf_9 = ifelse(Diff_Dens_surf_9 > 0.1, "Strat", "Not_Strat"))
  
  
#bind together, leaving all variables for now in case we want to keep or add 
strat_metrics <- left_join(fcr_dens, fcr_schmidt, by = "datetime")
strat_metrics <- left_join(strat_metrics, fcr_buoy, by = "datetime")

#trim to just metrics for plotting 
strat_metrics_long <- strat_metrics |> 
  select(-c(2:11)) |> #drop thermistor data 
  select(-Strat_1C_surf_9, -Strat_Dens0.1_surf_9) |> 
  pivot_longer(-1, names_to = "Variable", values_to = "Value") %>%
  rename(Date = datetime) %>%
  mutate(yday = yday(Date))

#write csv with strat metrics
write.csv(strat_metrics_long, "../01b_Processed_data/FCR_stratification_metrics.csv", row.names = F)
```

```{r}
met <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/389/8/d4c74bbb3b86ea293e5c52136347fbb0")

met_format <- met %>%
  mutate(Date = as.Date(DateTime),
         Year = year(Date)) %>%
  filter(Year == 2021) %>%
  group_by(Date) %>%
  summarize(AirTemp_C_Average = mean(AirTemp_C_Average, na.rm = T),
            Rain_Total_mm = sum(Rain_Total_mm),
            ShortwaveRadiationDown_Average_W_m2 = 
              mean(ShortwaveRadiationDown_Average_W_m2, na.rm = T)) %>%
  mutate(yday = yday(Date)) %>%
  pivot_longer(cols = c(AirTemp_C_Average,
                        Rain_Total_mm,
                        ShortwaveRadiationDown_Average_W_m2), 
               names_to = "Variable", values_to = "Value")

write.csv(met_format, "../01b_Processed_data/FCR_met.csv", row.names = F)
```

```{r}
ice <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/456/5/ebfaad16975326a7b874a21beb50c151")

#Note: it is always true that either IceOn == 1 or IceOff == 1

ice_format <- ice %>%
  filter(Reservoir == "FCR") %>%
  filter(Year == 2021) %>%
  mutate(Year = year(Date), 
         yday = yday(Date),
         Event = ifelse(IceOn == 1, "Ice on", "Ice off")) %>%
  group_by(yday, Date) %>%
  filter(!n() > 1) %>%
  ungroup() %>%
  select(Year, yday, Event)

write.csv(ice_format, "../01b_Processed_data/FCR_ice.csv", row.names = F)
```
