---
title: "Template"
author: "Abby Lewis"
date: "2024-03-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rLakeAnalyzer)
```

In-lake data (temperature, chlorophyll-a, stratification)

```{r}
# Load data
in_lake_data <- read.csv("../01a_Raw_data/YOUR LAKE.csv")

# Format continuous data
in_lake_formatted <- in_lake_data %>%
  mutate() #apply necessary transformations

write.csv(in_lake_formatted, "../01b_Processed_data/YOUR LAKE_continuous.csv", row.names = F)

# Stratification metric calcs (both discrete and continuous)

write.csv(strat_export_discrete, 
          "../01b_Processed_data/YOUR LAKE_stratification_discrete.csv", 
          row.names = F)
write.csv(strat_export_cont, 
          "../01b_Processed_data/YOUR LAKE_stratification_continuous.csv", 
          row.names = F)
```

Meteorological data

```{r}
# Load data
met <- read.csv("../01a_Raw_data/YOUR LAKE met.csv")

# Format continuous data
met_formatted <- met #apply necessary transformations

write.csv(met_formatted, "../01b_Processed_data/YOUR LAKE_met.csv", row.names = F)
```

Ice data

```{r}
#Load data
ice <- read.csv("../01a_Raw_data/YOUR LAKE ice.csv")

ice_formatted <- ice #apply necessary transformations

write.csv(ice_formatted, "../01b_Processed_data/YOUR LAKE_ice.csv", row.names = F)
```
